# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='para1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Lesson'),
        ),
        migrations.AddField(
            model_name='day',
            name='para2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a1', to='core.Lesson'),
        ),
        migrations.AddField(
            model_name='day',
            name='para3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a2', to='core.Lesson'),
        ),
        migrations.AddField(
            model_name='day',
            name='para4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a3', to='core.Lesson'),
        ),
        migrations.AddField(
            model_name='day',
            name='para5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a4', to='core.Lesson'),
        ),
        migrations.AlterField(
            model_name='day',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserGroup'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
